[project]
name = "test-project"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "ytra405-oss", email = "ytra405@aucklanduni.ac.nz" }
]
requires-python = ">=3.14"
dependencies = [
    "ipykernel>=7.3.0",
    "matplotlib>=3.11.1",
    "numpy>=2.5.1",
    "pandas>=3.0.5",
    "scipy>=1.18.0",
]

[project.scripts]
test-project = "test_project:main"

[build-system]
requires = ["uv_build>=0.12.0,<0.13.0"]
build-backend = "uv_build"
